/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScaleYourTeamRouteImport } from './routes/scale-your-team'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StartAProjectRouteImport } from './routes/start-a-project'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/_client/route'
import { Route as AuthenticatedDeveloperRouteRouteImport } from './routes/_authenticated/_developer/route'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesTeamAugmentationRouteImport } from './routes/services.team-augmentation'
import { Route as AuthenticatedClientPortalRouteImport } from './routes/_authenticated/_client/portal'
import { Route as AuthenticatedClientPortalDeliverablesRouteImport } from './routes/_authenticated/_client/portal-deliverables'
import { Route as AuthenticatedClientPortalInvoicesRouteImport } from './routes/_authenticated/_client/portal-invoices'
import { Route as AuthenticatedClientPortalProfileRouteImport } from './routes/_authenticated/_client/portal-profile'
import { Route as AuthenticatedClientPortalRequestsRouteImport } from './routes/_authenticated/_client/portal-requests'
import { Route as AuthenticatedDeveloperWorkspaceRouteImport } from './routes/_authenticated/_developer/workspace'
import { Route as AuthenticatedDeveloperWorkspaceProfileRouteImport } from './routes/_authenticated/_developer/workspace-profile'
import { Route as ApiAuthEmailHookRouteImport } from './routes/api/auth/email-hook'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminIdRouteImport } from './routes/_authenticated/_admin/admin.$id'
import { Route as AuthenticatedAdminAdminDeliveryRouteImport } from './routes/_authenticated/_admin/admin.delivery'
import { Route as AuthenticatedAdminAdminDocumentsRouteImport } from './routes/_authenticated/_admin/admin.documents'
import { Route as AuthenticatedAdminAdminLeadsRouteImport } from './routes/_authenticated/_admin/admin.leads'
import { Route as AuthenticatedAdminAdminNewRouteImport } from './routes/_authenticated/_admin/admin.new'
import { Route as AuthenticatedAdminAdminTeamRouteImport } from './routes/_authenticated/_admin/admin.team'
import { Route as ApiPublicBlogImageSplatRouteImport } from './routes/api/public/blog-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaleYourTeamRoute = ScaleYourTeamRouteImport.update({
  id: '/scale-your-team',
  path: '/scale-your-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAProjectRoute = StartAProjectRouteImport.update({
  id: '/start-a-project',
  path: '/start-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/_client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperRouteRoute =
  AuthenticatedDeveloperRouteRouteImport.update({
    id: '/_developer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTeamAugmentationRoute =
  ServicesTeamAugmentationRouteImport.update({
    id: '/services/team-augmentation',
    path: '/services/team-augmentation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientPortalRoute =
  AuthenticatedClientPortalRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientPortalDeliverablesRoute =
  AuthenticatedClientPortalDeliverablesRouteImport.update({
    id: '/portal-deliverables',
    path: '/portal-deliverables',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientPortalInvoicesRoute =
  AuthenticatedClientPortalInvoicesRouteImport.update({
    id: '/portal-invoices',
    path: '/portal-invoices',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientPortalProfileRoute =
  AuthenticatedClientPortalProfileRouteImport.update({
    id: '/portal-profile',
    path: '/portal-profile',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientPortalRequestsRoute =
  AuthenticatedClientPortalRequestsRouteImport.update({
    id: '/portal-requests',
    path: '/portal-requests',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedDeveloperWorkspaceRoute =
  AuthenticatedDeveloperWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedDeveloperRouteRoute,
  } as any)
const AuthenticatedDeveloperWorkspaceProfileRoute =
  AuthenticatedDeveloperWorkspaceProfileRouteImport.update({
    id: '/workspace-profile',
    path: '/workspace-profile',
    getParentRoute: () => AuthenticatedDeveloperRouteRoute,
  } as any)
const ApiAuthEmailHookRoute = ApiAuthEmailHookRouteImport.update({
  id: '/api/auth/email-hook',
  path: '/api/auth/email-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminIdRoute =
  AuthenticatedAdminAdminIdRouteImport.update({
    id: '/admin/$id',
    path: '/admin/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDeliveryRoute =
  AuthenticatedAdminAdminDeliveryRouteImport.update({
    id: '/admin/delivery',
    path: '/admin/delivery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDocumentsRoute =
  AuthenticatedAdminAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminLeadsRoute =
  AuthenticatedAdminAdminLeadsRouteImport.update({
    id: '/admin/leads',
    path: '/admin/leads',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminNewRoute =
  AuthenticatedAdminAdminNewRouteImport.update({
    id: '/admin/new',
    path: '/admin/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminTeamRoute =
  AuthenticatedAdminAdminTeamRouteImport.update({
    id: '/admin/team',
    path: '/admin/team',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicBlogImageSplatRoute = ApiPublicBlogImageSplatRouteImport.update({
  id: '/api/public/blog-image/$',
  path: '/api/public/blog-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scale-your-team': typeof ScaleYourTeamRoute
  '/search': typeof SearchRoute
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/team-augmentation': typeof ServicesTeamAugmentationRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/portal': typeof AuthenticatedClientPortalRoute
  '/portal-deliverables': typeof AuthenticatedClientPortalDeliverablesRoute
  '/portal-invoices': typeof AuthenticatedClientPortalInvoicesRoute
  '/portal-profile': typeof AuthenticatedClientPortalProfileRoute
  '/portal-requests': typeof AuthenticatedClientPortalRequestsRoute
  '/workspace': typeof AuthenticatedDeveloperWorkspaceRoute
  '/workspace-profile': typeof AuthenticatedDeveloperWorkspaceProfileRoute
  '/api/auth/email-hook': typeof ApiAuthEmailHookRoute
  '/admin/$id': typeof AuthenticatedAdminAdminIdRoute
  '/admin/delivery': typeof AuthenticatedAdminAdminDeliveryRoute
  '/admin/documents': typeof AuthenticatedAdminAdminDocumentsRoute
  '/admin/leads': typeof AuthenticatedAdminAdminLeadsRoute
  '/admin/new': typeof AuthenticatedAdminAdminNewRoute
  '/admin/team': typeof AuthenticatedAdminAdminTeamRoute
  '/api/public/blog-image/$': typeof ApiPublicBlogImageSplatRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scale-your-team': typeof ScaleYourTeamRoute
  '/search': typeof SearchRoute
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/team-augmentation': typeof ServicesTeamAugmentationRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/portal': typeof AuthenticatedClientPortalRoute
  '/portal-deliverables': typeof AuthenticatedClientPortalDeliverablesRoute
  '/portal-invoices': typeof AuthenticatedClientPortalInvoicesRoute
  '/portal-profile': typeof AuthenticatedClientPortalProfileRoute
  '/portal-requests': typeof AuthenticatedClientPortalRequestsRoute
  '/workspace': typeof AuthenticatedDeveloperWorkspaceRoute
  '/workspace-profile': typeof AuthenticatedDeveloperWorkspaceProfileRoute
  '/api/auth/email-hook': typeof ApiAuthEmailHookRoute
  '/admin/$id': typeof AuthenticatedAdminAdminIdRoute
  '/admin/delivery': typeof AuthenticatedAdminAdminDeliveryRoute
  '/admin/documents': typeof AuthenticatedAdminAdminDocumentsRoute
  '/admin/leads': typeof AuthenticatedAdminAdminLeadsRoute
  '/admin/new': typeof AuthenticatedAdminAdminNewRoute
  '/admin/team': typeof AuthenticatedAdminAdminTeamRoute
  '/api/public/blog-image/$': typeof ApiPublicBlogImageSplatRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scale-your-team': typeof ScaleYourTeamRoute
  '/search': typeof SearchRoute
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/_developer': typeof AuthenticatedDeveloperRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/team-augmentation': typeof ServicesTeamAugmentationRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/_client/portal': typeof AuthenticatedClientPortalRoute
  '/_authenticated/_client/portal-deliverables': typeof AuthenticatedClientPortalDeliverablesRoute
  '/_authenticated/_client/portal-invoices': typeof AuthenticatedClientPortalInvoicesRoute
  '/_authenticated/_client/portal-profile': typeof AuthenticatedClientPortalProfileRoute
  '/_authenticated/_client/portal-requests': typeof AuthenticatedClientPortalRequestsRoute
  '/_authenticated/_developer/workspace': typeof AuthenticatedDeveloperWorkspaceRoute
  '/_authenticated/_developer/workspace-profile': typeof AuthenticatedDeveloperWorkspaceProfileRoute
  '/api/auth/email-hook': typeof ApiAuthEmailHookRoute
  '/_authenticated/_admin/admin/$id': typeof AuthenticatedAdminAdminIdRoute
  '/_authenticated/_admin/admin/delivery': typeof AuthenticatedAdminAdminDeliveryRoute
  '/_authenticated/_admin/admin/documents': typeof AuthenticatedAdminAdminDocumentsRoute
  '/_authenticated/_admin/admin/leads': typeof AuthenticatedAdminAdminLeadsRoute
  '/_authenticated/_admin/admin/new': typeof AuthenticatedAdminAdminNewRoute
  '/_authenticated/_admin/admin/team': typeof AuthenticatedAdminAdminTeamRoute
  '/api/public/blog-image/$': typeof ApiPublicBlogImageSplatRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/reset-password'
    | '/scale-your-team'
    | '/search'
    | '/start-a-project'
    | '/terms'
    | '/unauthorized'
    | '/account'
    | '/onboarding'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/services/team-augmentation'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/services/'
    | '/portal'
    | '/portal-deliverables'
    | '/portal-invoices'
    | '/portal-profile'
    | '/portal-requests'
    | '/workspace'
    | '/workspace-profile'
    | '/api/auth/email-hook'
    | '/admin/$id'
    | '/admin/delivery'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/new'
    | '/admin/team'
    | '/api/public/blog-image/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/reset-password'
    | '/scale-your-team'
    | '/search'
    | '/start-a-project'
    | '/terms'
    | '/unauthorized'
    | '/account'
    | '/onboarding'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/services/team-augmentation'
    | '/case-studies'
    | '/industries'
    | '/insights'
    | '/services'
    | '/portal'
    | '/portal-deliverables'
    | '/portal-invoices'
    | '/portal-profile'
    | '/portal-requests'
    | '/workspace'
    | '/workspace-profile'
    | '/api/auth/email-hook'
    | '/admin/$id'
    | '/admin/delivery'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/new'
    | '/admin/team'
    | '/api/public/blog-image/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/reset-password'
    | '/scale-your-team'
    | '/search'
    | '/start-a-project'
    | '/terms'
    | '/unauthorized'
    | '/_authenticated/_admin'
    | '/_authenticated/_client'
    | '/_authenticated/_developer'
    | '/_authenticated/account'
    | '/_authenticated/onboarding'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/services/team-augmentation'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/services/'
    | '/_authenticated/_client/portal'
    | '/_authenticated/_client/portal-deliverables'
    | '/_authenticated/_client/portal-invoices'
    | '/_authenticated/_client/portal-profile'
    | '/_authenticated/_client/portal-requests'
    | '/_authenticated/_developer/workspace'
    | '/_authenticated/_developer/workspace-profile'
    | '/api/auth/email-hook'
    | '/_authenticated/_admin/admin/$id'
    | '/_authenticated/_admin/admin/delivery'
    | '/_authenticated/_admin/admin/documents'
    | '/_authenticated/_admin/admin/leads'
    | '/_authenticated/_admin/admin/new'
    | '/_authenticated/_admin/admin/team'
    | '/api/public/blog-image/$'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScaleYourTeamRoute: typeof ScaleYourTeamRoute
  SearchRoute: typeof SearchRoute
  StartAProjectRoute: typeof StartAProjectRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesTeamAugmentationRoute: typeof ServicesTeamAugmentationRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiAuthEmailHookRoute: typeof ApiAuthEmailHookRoute
  ApiPublicBlogImageSplatRoute: typeof ApiPublicBlogImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scale-your-team': {
      id: '/scale-your-team'
      path: '/scale-your-team'
      fullPath: '/scale-your-team'
      preLoaderRoute: typeof ScaleYourTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-project': {
      id: '/start-a-project'
      path: '/start-a-project'
      fullPath: '/start-a-project'
      preLoaderRoute: typeof StartAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_client': {
      id: '/_authenticated/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_developer': {
      id: '/_authenticated/_developer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/team-augmentation': {
      id: '/services/team-augmentation'
      path: '/services/team-augmentation'
      fullPath: '/services/team-augmentation'
      preLoaderRoute: typeof ServicesTeamAugmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_client/portal': {
      id: '/_authenticated/_client/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedClientPortalRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/portal-deliverables': {
      id: '/_authenticated/_client/portal-deliverables'
      path: '/portal-deliverables'
      fullPath: '/portal-deliverables'
      preLoaderRoute: typeof AuthenticatedClientPortalDeliverablesRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/portal-invoices': {
      id: '/_authenticated/_client/portal-invoices'
      path: '/portal-invoices'
      fullPath: '/portal-invoices'
      preLoaderRoute: typeof AuthenticatedClientPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/portal-profile': {
      id: '/_authenticated/_client/portal-profile'
      path: '/portal-profile'
      fullPath: '/portal-profile'
      preLoaderRoute: typeof AuthenticatedClientPortalProfileRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/portal-requests': {
      id: '/_authenticated/_client/portal-requests'
      path: '/portal-requests'
      fullPath: '/portal-requests'
      preLoaderRoute: typeof AuthenticatedClientPortalRequestsRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_developer/workspace': {
      id: '/_authenticated/_developer/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedDeveloperWorkspaceRouteImport
      parentRoute: typeof AuthenticatedDeveloperRouteRoute
    }
    '/_authenticated/_developer/workspace-profile': {
      id: '/_authenticated/_developer/workspace-profile'
      path: '/workspace-profile'
      fullPath: '/workspace-profile'
      preLoaderRoute: typeof AuthenticatedDeveloperWorkspaceProfileRouteImport
      parentRoute: typeof AuthenticatedDeveloperRouteRoute
    }
    '/api/auth/email-hook': {
      id: '/api/auth/email-hook'
      path: '/api/auth/email-hook'
      fullPath: '/api/auth/email-hook'
      preLoaderRoute: typeof ApiAuthEmailHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/$id': {
      id: '/_authenticated/_admin/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/delivery': {
      id: '/_authenticated/_admin/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/documents': {
      id: '/_authenticated/_admin/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/leads': {
      id: '/_authenticated/_admin/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/new': {
      id: '/_authenticated/_admin/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/team': {
      id: '/_authenticated/_admin/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/blog-image/$': {
      id: '/api/public/blog-image/$'
      path: '/api/public/blog-image/$'
      fullPath: '/api/public/blog-image/$'
      preLoaderRoute: typeof ApiPublicBlogImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminIdRoute: typeof AuthenticatedAdminAdminIdRoute
  AuthenticatedAdminAdminDeliveryRoute: typeof AuthenticatedAdminAdminDeliveryRoute
  AuthenticatedAdminAdminDocumentsRoute: typeof AuthenticatedAdminAdminDocumentsRoute
  AuthenticatedAdminAdminLeadsRoute: typeof AuthenticatedAdminAdminLeadsRoute
  AuthenticatedAdminAdminNewRoute: typeof AuthenticatedAdminAdminNewRoute
  AuthenticatedAdminAdminTeamRoute: typeof AuthenticatedAdminAdminTeamRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminIdRoute: AuthenticatedAdminAdminIdRoute,
    AuthenticatedAdminAdminDeliveryRoute: AuthenticatedAdminAdminDeliveryRoute,
    AuthenticatedAdminAdminDocumentsRoute:
      AuthenticatedAdminAdminDocumentsRoute,
    AuthenticatedAdminAdminLeadsRoute: AuthenticatedAdminAdminLeadsRoute,
    AuthenticatedAdminAdminNewRoute: AuthenticatedAdminAdminNewRoute,
    AuthenticatedAdminAdminTeamRoute: AuthenticatedAdminAdminTeamRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientPortalRoute: typeof AuthenticatedClientPortalRoute
  AuthenticatedClientPortalDeliverablesRoute: typeof AuthenticatedClientPortalDeliverablesRoute
  AuthenticatedClientPortalInvoicesRoute: typeof AuthenticatedClientPortalInvoicesRoute
  AuthenticatedClientPortalProfileRoute: typeof AuthenticatedClientPortalProfileRoute
  AuthenticatedClientPortalRequestsRoute: typeof AuthenticatedClientPortalRequestsRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientPortalRoute: AuthenticatedClientPortalRoute,
    AuthenticatedClientPortalDeliverablesRoute:
      AuthenticatedClientPortalDeliverablesRoute,
    AuthenticatedClientPortalInvoicesRoute:
      AuthenticatedClientPortalInvoicesRoute,
    AuthenticatedClientPortalProfileRoute:
      AuthenticatedClientPortalProfileRoute,
    AuthenticatedClientPortalRequestsRoute:
      AuthenticatedClientPortalRequestsRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedDeveloperRouteRouteChildren {
  AuthenticatedDeveloperWorkspaceRoute: typeof AuthenticatedDeveloperWorkspaceRoute
  AuthenticatedDeveloperWorkspaceProfileRoute: typeof AuthenticatedDeveloperWorkspaceProfileRoute
}

const AuthenticatedDeveloperRouteRouteChildren: AuthenticatedDeveloperRouteRouteChildren =
  {
    AuthenticatedDeveloperWorkspaceRoute: AuthenticatedDeveloperWorkspaceRoute,
    AuthenticatedDeveloperWorkspaceProfileRoute:
      AuthenticatedDeveloperWorkspaceProfileRoute,
  }

const AuthenticatedDeveloperRouteRouteWithChildren =
  AuthenticatedDeveloperRouteRoute._addFileChildren(
    AuthenticatedDeveloperRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedDeveloperRouteRoute: typeof AuthenticatedDeveloperRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedDeveloperRouteRoute:
    AuthenticatedDeveloperRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScaleYourTeamRoute: ScaleYourTeamRoute,
  SearchRoute: SearchRoute,
  StartAProjectRoute: StartAProjectRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesTeamAugmentationRoute: ServicesTeamAugmentationRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiAuthEmailHookRoute: ApiAuthEmailHookRoute,
  ApiPublicBlogImageSplatRoute: ApiPublicBlogImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
